name: Trigger tests manually

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      run:
        type: boolean
        description: ''
        required: false
      testomatio:
        type: boolean
        description: ''
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Execute tests with Maven
      env:
        TESTOMATIO: ${{ github.event.inputs.testomatio }}
        TESTOMATIO_RUN: ${{ github.event.inputs.run }}
      run: |
        echo "testomatio: " ${{ github.event.inputs.testomatio }}
        echo "testomatio_run: " ${{ github.event.inputs.run }}
        mvn clean test

  testomat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Execute collection of metrics to the Testomat
        run: |
          TESTOMATIO=455911d76f74 npx report-xml "/target/surefire-reports/**.xml" --java-tests=src/test/java
          echo pwd